config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  root 'welcome#index'

  resources :artists do
    resources :bands 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord

  has_many :bands, foreign_key: "group_id",  dependent: :destroy 


  has_many :individuals, :through => :bands, :source => :artist

  has_many :groups, :through => :bands, :source => :artist
  accepts_nested_attributes_for :bands

  validates :name, presence: true,
                    length: { maximum: 25 }	
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :individual, class_name: "Artist", inverse_of: :bands
  belongs_to :group, class_name: "Artist", inverse_of: :bands
  validates :creation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artisti_controller.rb
class ArtistiController < ApplicationController
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
 def index
    @artists = Artist.all
  end
 
  def show
    @artist = Artist.find(params[:id])
  end
 
  def new
    @artist = Artist.new
    @artist.isgroup = false
  end
 
  def edit
    @artist = Artist.find(params[:id])
  end
 
  def create
    @artist = Artist.new(artist_params)
 
    if @artist.save
      redirect_to @artist
    else
      render 'new'
    end
  end
 
  def update
    @artist = Artist.find(params[:id])
 
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render 'edit'
    end
  end
 
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
 
    redirect_to artists_path
  end
 
  private
    def artist_params
      params.require(:artist).permit(:name, :bio, :isgroup, bands_attributes: [:id, :individual_id, :group_id, :creation, :disbanding])
    end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
  end
 
  def show
    @band = Band.find(params[:id])
  end
 
  def new
    @band = Band.new
    #@band = @artist.bands.build

  end
 
  def edit
    @band = Band.find(params[:id])

  end
 
  def create
    #@band = Band.new(band_params)
    #band.song =@song
    @group = Artist.find(params[:artist_id])
    @band = @group.bands.create(band_params)

    if @band.save
      redirect_to artist_path(@group)
    else
 
     @artist = Artist.find(params[:artist_id])
     render 'artists/show'
    end
  end

  def update
    @group = Artist.find(params[:artist_id])
    @band = @group.find(params[:id])
    if @band.update(band_params)
      redirect_to_edit_artist_path(@group)
    else 
      render 'edit' 
    end
  end

  private
    def band_params
      params.require(:band).permit(:individual_id, :group_id, :creation,:disbanding)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artisti_helper.rb
module ArtistiHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/artists/_artistinfo.html.erb
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :bio %><br>
    <%= f.text_area :bio, size: "30x10" %>
  </p>

  <p>

    <%= f.radio_button(:isgroup, false)  %>
    <%= label_tag( "Single artist") %>
    <%= f.radio_button(:isgroup, true) %>
    <%= label_tag( "A group of artists") %>
  </p>

app/views/artists/_errors.html.erb
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@artist.errors.count, "error") %> prohibited
        this artist from being saved:
      </h2>
      <ul>
        <% @artist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

<%= render 'errors' %>

<%= render 'artistinfo' %>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= form_for @artist do |f| %>

<%= render 'errors' %>

  <%= render 'artistinfo', f: f %>

  <% if @artist.isgroup %>
    <h2>Edit a member of the group</h2>
    <% @artist.bands.each do |band| %> 
      <%= f.fields_for :bands, band do |ff| %>
      <h4><%=band.individual.name%> </h4>
      <h5> Joining date </h5>
      <%= ff.date_field :creation %><br> 
      <h5> Leaving date </h5>
      <%= ff.date_field :disbanding %><br> 


     <% end %>
   <% end %>
  <% end %>
  <p>
    <%= f.submit %>
  </p>

<% end %>
 
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Listing Artists</h1>
<%= link_to 'New artist', new_artist_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
 
  <% @artists.each do |artist| %>
    <tr>
      <td><%= artist.name %></td>
      <% if artist.isgroup %>
        <td>Group</td>
      <% else %>
        <td>Individual</td>
      <% end %>
      <td><%= link_to 'Show', artist_path(artist) %></td>
      <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
      <td><%= link_to 'Destroy', artist_path(artist),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back', welcome_index_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= form_for @artist do |f| %>

  <%= render 'errors' %>

  <%= render 'artistinfo', f: f %>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<%= render 'errors' %>
<p>
  <strong>Name:</strong>
  <%= @artist.name %>

</p>
 
<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>

</p>

<p>
 
  <% if @artist.isgroup %>
    <h2>
      Group of artists
    </h2>
    <h6>
      A group should have at least one member
    </h6>
      <h2>Members of the group</h2>
      <table>
        <tr>
        <th>Name</th>
        <th>Joining date</th>
        <th>Leaving date</th>
        <th colspan="1"></th>
      </tr>
      <% @artist.bands.each do |band| %>
        <tr>
        <td><%= band.individual.name %></td>
        <td><%= band.creation %></td>
        <td><%= band.disbanding %></td>
        <td><%= link_to 'Edit', edit_artist_path(band.individual) %></td>
      </tr>  
      <% end %>
      </table>



      <%# @group = @artist %>  

      <h2> Add a member to the group:   </h2>

      <%= form_for([@artist, @artist.bands.build]) do |ff| %>
        <p>
          <%= ff.select :individual_id, Artist.where(:isgroup=>false).collect{ |p| [p.name, p.id] } %><br>
        </p>
        <p>
          <h5> Joining date </h5>
          <%= ff.date_field :creation %>
        </p>
        <p>
          <h5> Leaving date </h5>
          <%= ff.date_field :disbanding %>
        </p>

 

        <p>
        <%= ff.submit %>
        </p>

     <% end %>	

  <% else %>   
    <h2>
      Single artist
    </h2>
    <% if false %>
       <table>
        <tr>
        <th>Name</th>
        <th>Joining date</th>
        <th>Leaving date</th>
        <th colspan="1"></th>
      </tr>
      <% @artist.bands.each do |band| %>
        <tr>
        <td><%= band.group.name %></td>
        <td><%= band.creation %></td>
        <td><%= band.disbanding %></td>
        <td><%= link_to 'Edit', edit_artist_path(band.individual) %></td>
      </tr>  
      <% end %>
      </table>      
    <% end %>  
  <% end %>
</p>



<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Add another artist', new_artist_path %> |
<%= link_to 'Back', artists_path %>

app/views/bands/_errors.html.erb
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@band.errors.count, "error") %> prohibited
        this band from being saved:
      </h2>
      <ul>
        <% @band.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artisti</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p><%= link_to "Artist", artists_path %></p>